# Generated by Django 5.2.17 on 2026-10-03 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WarmupJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="running", max_length=16)),
                ("messages", models.JSONField()),
                ("started_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("error", models.CharField(blank=True, max_length=255)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WarmupParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("next_message_at", models.DateTimeField()),
                ("sent", models.PositiveIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="accounts.warmupjob",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="warmupjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "running")),
                fields=("owner",),
                name="one_running_warmup_per_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="warmupparticipant",
            constraint=models.UniqueConstraint(
                fields=("job", "account"), name="unique_warmup_participant"
            ),
        ),
    ]
