# Generated by Django 5.2.17 on 2026-10-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_remove_publicationbatch_verifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="check_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="session_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="session_error",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="account",
            name="session_status",
            field=models.CharField(default="unchecked", max_length=16),
        ),
        migrations.AddField(
            model_name="account",
            name="spam_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="spam_detail",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="account",
            name="spam_status",
            field=models.CharField(default="unchecked", max_length=16),
        ),
        migrations.AddField(
            model_name="warmupparticipant",
            name="error",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="warmupparticipant",
            name="failures",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
